// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeModelFile(arg1) {
  return window['go']['main']['App']['AnalyzeModelFile'](arg1);
}

export function ImportModelFiles() {
  return window['go']['main']['App']['ImportModelFiles']();
}

export function ReadModelForUpload(arg1) {
  return window['go']['main']['App']['ReadModelForUpload'](arg1);
}

export function ReadPreviewModel(arg1) {
  return window['go']['main']['App']['ReadPreviewModel'](arg1);
}
