// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AnalyzeModelFile(arg1:string):Promise<main.ModelAnalysis>;

export function ImportModelFiles():Promise<Array<main.ModelAnalysis>>;

export function ReadModelForUpload(arg1:string):Promise<main.UploadModelPayload>;

export function ReadPreviewModel(arg1:string):Promise<main.PreviewModelPayload>;
